### ISSUE TITLE
How to remove deleted node from root

### ISSUE THREAD

**Issue by Namanjain010** [nextjs-boilerplate/components#2]
Thanks for solving my previous issue, it's working but still I can see the deleted node inside root data while printing it in console

**Comment by postor** [comment]
https://github.com/postor/react-tree-renderer#with-event--%E4%BD%BF%E7%94%A8%E4%BA%8B%E4%BB%B6   if you want a clean solution now, you can use event, this way is more clean but need more code, suggest try the event example first, you can get the basic idea of event, and customize it to your use case

to delete the node, you trigger an event in template and handle in container, you can get the triggered path, and follow the path you can find it's parent, then update the parent's `children`, please try on your own first
