### ISSUE TITLE
Error in your delete child code, when you delete test1 child you will see the error that the Attribute value of test1 is shown in test2 node which was empty

### ISSUE THREAD

**Issue by Namanjain010** [nextjs-boilerplate/components#5]
`import React from 'react'
import TreeRenderer from 'react-tree-renderer'

class DefaultTemplate extends React.Component {

    handleAddChild() {
        const { data = {}, updateData, } = this.props
        const { children = [] } = data
    
        updateData({
          ...data,
          children: [
            ...children,
            { title: 'new' },
          ]
        })
      }
  //modify title | 修改title
  handleUpdateTitle(e) {
    // get updateData from props | 从props中获取updateData
    const { data = {}, updateData, } = this.props
    const title = e.target.value

    // and call updateData when you need | 并使用updateData方法更新对应节点的数据
    updateData({
      ...data,
      title
    })
  }
  handleUpdateAttribute(e){
    const { data = {}, updateData, } = this.props
    const Attribute = e.target.value

    // and call updateData when you need | 并使用updateData方法更新对应节点的数据
    updateData({
      ...data,
      Attribute
    })

  }
  render() {
    const { data = {}, children = [], deleteMe, isRoot } = this.props
    return (
      <div>
        <input value={data.title} onChange={this.handleUpdateTitle.bind(this)} />
        <input value={data.Attribute} onChange={this.handleUpdateAttribute.bind(this)} />
        <button onClick={this.handleAddChild.bind(this)}>+</button>
        
        {!isRoot && <button onClick={() => deleteMe()}>x</button>}
        <ul>
          {children.map((x, i) => (<li key={i}>{x}</li>))}
        </ul>
        
      </div>
    )
  }
}

export default class TestTree extends React.Component {
  constructor(props, ctx) {
    super(props, ctx)
    this.state = {
      root: {
        title: 'root',
        children: [
          {
            title: 'root',
            Attribute:"Bye",
            children: [
              {
                title: 'test1',
                Attribute:"Hii",
              },
              {
                title: 'test2',
              }
            ]
          },
          {    
          title: 'root2',
          Attribute:"who",
          children: [
            {
              title: 'test3',
              Attribute:"Why",
            }
          ]
        }  
        ]
      }
    }
  }

  render() {
    const { root = {} } = this.state
    console.log(JSON.stringify(root))
    return (<TreeRenderer Template={DefaultTemplate} data={root} onUpdateData={(root) => this.setState({ root, })} />)
  }
}`

**Comment by postor** [comment]
added code for add/delete/update in one, hope this can help you
![screenshot](https://user-images.githubusercontent.com/699002/84458995-ec702380-ac98-11ea-917b-00bed2a92160.gif)
