### ISSUE TITLE
Thanks for updating the code in one but that's not what i wanted the issue remains the same

### ISSUE THREAD

**Issue by Namanjain010** [nextjs-boilerplate/components#6]
When I try to delete node with title "test1" and second value as "Hii", although the node gets deleted we can see the second value("Hii") of a deleted node in next node with title name "test2" which was empty initially, these are the 2 images first one initial and second one after deletion
![1](https://user-images.githubusercontent.com/34453750/84463582-dad64e00-ac8f-11ea-94d4-6573953e178b.PNG)
![2](https://user-images.githubusercontent.com/34453750/84463587-de69d500-ac8f-11ea-8472-0ce13d4a8948.PNG)

**Comment by postor** [comment]
can you provide your project, or code sandbox?

**Comment by Namanjain010** [comment]
https://codesandbox.io/s/link-bdmys?file=/src/vip.js

**Comment by postor** [comment]
why don't you handle errors in console? you just need a default value
![screenshot1](https://user-images.githubusercontent.com/699002/84478792-741f5780-acc4-11ea-96fb-017154b5196f.gif)
